on:
  workflow_dispatch
  
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Github Action for LaTeX
        uses: xu-cheng/latex-action@v2
